# Development environment. This environment includes all the required
# packages for this repo including running the test suite.
name: pyleo
channels:
  - conda-forge
  - default
dependencies:
  - python>=3.9
  - cartopy
  - numba
  - pyyaml
  - requests
  - scikit-learn
  - seaborn
  - statsmodels
  - tabulate
  - tqdm
  - wget
  - pip
  - pip:
    - pyhht
    - '-e .'
