name: Build container image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@Development

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@Development
      with: # make sure username & password/token matches your registry
        DOCKER_USERNAME: ${{ secrets.QUAY_DEV_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_DEV_PASSWORD }}
        DOCKER_REGISTRY: "quay.io"
        IMAGE_NAME: "linkedearth/pyleoclim-dev"
