name: run pytest for the Development Branch

on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    - name: checkout files in repo
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pyleo
        environment-file: environment.yml
        python-version: 3.10
        channels: conda-forge,defaults
        channel-priority: true
        auto-activate-base: false

    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest
